In [62]:
import pandas as pd
import numpy as np

In [63]:
dataset=pd.read_csv("D:\csv files\Brain Stroke.csv")

In [64]:
dataset

gender   age  hypertension  heart_disease ever_married      work_type  \
0       Male  67.0             0              1          Yes        Private   
1       Male  80.0             0              1          Yes        Private   
2     Female  49.0             0              0          Yes        Private   
3     Female  79.0             1              0          Yes  Self-employed   
4       Male  81.0             0              0          Yes        Private   
...      ...   ...           ...            ...          ...            ...   
4976    Male  41.0             0              0           No        Private   
4977    Male  40.0             0              0          Yes        Private   
4978  Female  45.0             1              0          Yes       Govt_job   
4979    Male  40.0             0              0          Yes        Private   
4980  Female  80.0             1              0          Yes        Private   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             105.92  32.5     never smoked       1  
2             Urban             171.23  34.4           smokes       1  
3             Rural             174.12  24.0     never smoked       1  
4             Urban             186.21  29.0  formerly smoked       1  
...             ...                ...   ...              ...     ...  
4976          Rural              70.15  29.8  formerly smoked       0  
4977          Urban             191.15  31.1           smokes       0  
4978          Rural              95.02  31.8           smokes       0  
4979          Rural              83.94  30.0           smokes       0  
4980          Urban              83.75  29.1     never smoked       0  

[4981 rows x 11 columns]

In [65]:
dataset["ever_married"]=dataset["ever_married"].map({'Yes':1,'No':0})
dataset["work_type"]=dataset["work_type"].map({'Private':0,'Self-employed':1,'Govt_job':2,'children':3})
dataset["Residence_type"]=dataset["Residence_type"].map({'Urban':0,'Rural':1})
dataset["smoking_status"]=dataset["smoking_status"].map({'formerly smoked':0,'never smoked':1,'smokes':2,'Unknown':3})

In [66]:
dataset

gender   age  hypertension  heart_disease  ever_married  work_type  \
0       Male  67.0             0              1             1          0   
1       Male  80.0             0              1             1          0   
2     Female  49.0             0              0             1          0   
3     Female  79.0             1              0             1          1   
4       Male  81.0             0              0             1          0   
...      ...   ...           ...            ...           ...        ...   
4976    Male  41.0             0              0             0          0   
4977    Male  40.0             0              0             1          0   
4978  Female  45.0             1              0             1          2   
4979    Male  40.0             0              0             1          0   
4980  Female  80.0             1              0             1          0   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  0             228.69  36.6               0       1  
1                  1             105.92  32.5               1       1  
2                  0             171.23  34.4               2       1  
3                  1             174.12  24.0               1       1  
4                  0             186.21  29.0               0       1  
...              ...                ...   ...             ...     ...  
4976               1              70.15  29.8               0       0  
4977               0             191.15  31.1               2       0  
4978               1              95.02  31.8               2       0  
4979               1              83.94  30.0               2       0  
4980               0              83.75  29.1               1       0  

[4981 rows x 11 columns]

In [67]:
dataset["gender"]=dataset["gender"].map({'Male':1,'Female':0})

In [68]:
dataset

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          0   
1          1  80.0             0              1             1          0   
2          0  49.0             0              0             1          0   
3          0  79.0             1              0             1          1   
4          1  81.0             0              0             1          0   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          0   
4977       1  40.0             0              0             1          0   
4978       0  45.0             1              0             1          2   
4979       1  40.0             0              0             1          0   
4980       0  80.0             1              0             1          0   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  0             228.69  36.6               0       1  
1                  1             105.92  32.5               1       1  
2                  0             171.23  34.4               2       1  
3                  1             174.12  24.0               1       1  
4                  0             186.21  29.0               0       1  
...              ...                ...   ...             ...     ...  
4976               1              70.15  29.8               0       0  
4977               0             191.15  31.1               2       0  
4978               1              95.02  31.8               2       0  
4979               1              83.94  30.0               2       0  
4980               0              83.75  29.1               1       0  

[4981 rows x 11 columns]

In [69]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [70]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scale=scaler.fit_transform(x)

In [71]:
print(scale)

[[ 1.18390850e+00  1.04058433e+00 -3.26185770e-01 ...  2.72341090e+00
   1.19323816e+00 -1.45002710e+00]
 [ 1.18390850e+00  1.61427033e+00 -3.26185770e-01 ... -5.22766599e-04
   5.89389611e-01 -5.34617090e-01]
 [-8.44659868e-01  2.46249882e-01 -3.26185770e-01 ...  1.44852918e+00
   8.69221866e-01  3.80792922e-01]
 ...
 [-8.44659868e-01  6.97311148e-02  3.06573766e+00 ... -2.42364234e-01
   4.86293516e-01  3.80792922e-01]
 [ 1.18390850e+00 -1.50917344e-01 -3.26185770e-01 ... -4.88199415e-01
   2.21189274e-01  3.80792922e-01]
 [-8.44659868e-01  1.61427033e+00  3.06573766e+00 ... -4.92415000e-01
   8.86371531e-02 -5.34617090e-01]]


In [38]:
from sklearn.model_selection import train_test_split
scale_train,scale_test,y_train,y_test=train_test_split(scale,y,test_size=0.2,random_state=9)

In [39]:
from sklearn.linear_model import LogisticRegression
re=LogisticRegression()
re.fit(scale_train,y_train)

LogisticRegression()

In [40]:
y_pred=re.predict(scale_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [41]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [73]:
scale.max()

4.136753228405977

In [72]:
scale.min()

-2.1352928787181042

In [47]:
dataset

gender   age  hypertension  heart_disease  ever_married  work_type  \
0          1  67.0             0              1             1          0   
1          1  80.0             0              1             1          0   
2          0  49.0             0              0             1          0   
3          0  79.0             1              0             1          1   
4          1  81.0             0              0             1          0   
...      ...   ...           ...            ...           ...        ...   
4976       1  41.0             0              0             0          0   
4977       1  40.0             0              0             1          0   
4978       0  45.0             1              0             1          2   
4979       1  40.0             0              0             1          0   
4980       0  80.0             1              0             1          0   

      Residence_type  avg_glucose_level   bmi  smoking_status  stroke  
0                  0             228.69  36.6               0       1  
1                  1             105.92  32.5               1       1  
2                  0             171.23  34.4               2       1  
3                  1             174.12  24.0               1       1  
4                  0             186.21  29.0               0       1  
...              ...                ...   ...             ...     ...  
4976               1              70.15  29.8               0       0  
4977               0             191.15  31.1               2       0  
4978               1              95.02  31.8               2       0  
4979               1              83.94  30.0               2       0  
4980               0              83.75  29.1               1       0  

[4981 rows x 11 columns]

In [48]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [49]:
from sklearn.preprocessing import MinMaxScaler
ab=MinMaxScaler()
scale=ab.fit_transform(x)

In [50]:
from sklearn.model_selection import train_test_split
scale_train,scale_test,y_train,y_test=train_test_split(scale,y,test_size=0.1,random_state=9)

In [51]:
from sklearn.linear_model import LogisticRegression
re=LogisticRegression()
re.fit(scale_train,y_train)

LogisticRegression()

In [52]:
y_pred=re.predict(scale_test)

In [53]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [54]:
y_test

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)*100

94.58917835671342

In [56]:
scale.max()

1.0

In [57]:
scale.min()

0.0